## Data Validation

Prerequisite: Port-Forward Service  
Terminal 1: Port-forward MinIO (for data access)  
```
kubectl port-forward -n mldata svc/mlminio 9000:9000
```

In [1]:
import polars as pl
import boto3
import mlflow
import os
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()

/mnt/e/Repos/Projects/ML-Model-Factory/.venv/lib/python3.10/site-packages/mlflow/utils/requirements_utils.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources  # noqa: TID251

True

In [2]:
aws_access_key_id = os.getenv("AWS_ACCESS_KEY_ID")
aws_secret_access_key = os.getenv("AWS_SECRET_ACCESS_KEY")
endpoint_url = os.getenv("MLFLOW_S3_ENDPOINT_URL")
bucket_name = os.getenv("BUCKET_NAME")
bucket_key = os.getenv("BUCKET_KEY")

s3 = boto3.client(
    "s3",
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    endpoint_url=endpoint_url
)
bucket_key

'mobile_sales_data.csv'

In [3]:
obj=s3.get_object(Bucket=bucket_name, Key=bucket_key)
obj

{'ResponseMetadata': {'RequestId': '18D09756B68CCB8B',
  'HostId': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'accept-ranges': 'bytes',
   'content-length': '4536112',
   'content-type': 'text/csv',
   'etag': '"2884ebc2b9e905129728cfcb699376e2"',
   'last-modified': 'Sun, 30 Aug 2026 05:40:40 GMT',
   'server': 'MinIO',
   'strict-transport-security': 'max-age=31536000; includeSubDomains',
   'vary': 'Origin, Accept-Encoding',
   'x-amz-id-2': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
   'x-amz-request-id': '18D09756B68CCB8B',
   'x-content-type-options': 'nosniff',
   'x-ratelimit-limit': '608',
   'x-ratelimit-remaining': '608',
   'x-xss-protection': '1; mode=block',
   'date': 'Sun, 30 Aug 2026 13:10:50 GMT'},
  'RetryAttempts': 0},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 8, 30, 5, 40, 40, tzinfo=tzutc()),
 'ContentLength': 4536112,
 'ETag': '"2884ebc2b9e905129728cfcb699376e2"',
 'ContentType': 'text/csv',
 'Metadata': {},
 'Body': <botocore.response.StreamingBody at 0x7699bf17b4c0>}

In [4]:
df = pl.read_csv(obj['Body'])
len(df)

24983

In [5]:
df.describe()

shape: (9, 15)
┌────────────┬──────────────┬───────┬──────────────┬───┬─────────┬─────────────────┬───────┬───────┐
│ describe   ┆ Product      ┆ Brand ┆ Product Code ┆ … ┆ Region  ┆ Processor       ┆ RAM   ┆ ROM   │
│ ---        ┆ ---          ┆ ---   ┆ ---          ┆   ┆ ---     ┆ Specification   ┆ ---   ┆ ---   │
│ str        ┆ str          ┆ str   ┆ str          ┆   ┆ str     ┆ ---             ┆ str   ┆ str   │
│            ┆              ┆       ┆              ┆   ┆         ┆ str             ┆       ┆       │
╞════════════╪══════════════╪═══════╪══════════════╪═══╪═════════╪═════════════════╪═══════╪═══════╡
│ count      ┆ 24983        ┆ 24983 ┆ 24983        ┆ … ┆ 24983   ┆ 24983           ┆ 24983 ┆ 24983 │
│ null_count ┆ 0            ┆ 0     ┆ 0            ┆ … ┆ 0       ┆ 0               ┆ 0     ┆ 0     │
│ mean       ┆ null         ┆ null  ┆ null         ┆ … ┆ null    ┆ null            ┆ null  ┆ null  │
│ std        ┆ null         ┆ null  ┆ null         ┆ … ┆ null    ┆ null            ┆ null  ┆ null  │
│ min        ┆ Mobile Phone ┆ Acer  ┆ 0004C0C5     ┆ … ┆ Central ┆ Apple A-Series  ┆ 12GB  ┆ 128GB │
│ 25%        ┆ null         ┆ null  ┆ null         ┆ … ┆ null    ┆ null            ┆ null  ┆ null  │
│ 50%        ┆ null         ┆ null  ┆ null         ┆ … ┆ null    ┆ null            ┆ null  ┆ null  │
│ 75%        ┆ null         ┆ null  ┆ null         ┆ … ┆ null    ┆ null            ┆ null  ┆ null  │
│ max        ┆ Mobile Phone ┆ iQOO  ┆ FFFEE3D7     ┆ … ┆ West    ┆ Snapdragon 8    ┆ 8GB   ┆ 64GB  │
│            ┆              ┆       ┆              ┆   ┆         ┆ Gen             ┆       ┆       │
└────────────┴──────────────┴───────┴──────────────┴───┴─────────┴─────────────────┴───────┴───────┘

In [6]:
df.head()

shape: (5, 14)
┌─────────┬──────────┬────────────────┬───────────────┬───┬─────────┬───────────────┬──────┬───────┐
│ Product ┆ Brand    ┆ Product Code   ┆ Product       ┆ … ┆ Region  ┆ Processor     ┆ RAM  ┆ ROM   │
│ ---     ┆ ---      ┆ ---            ┆ Specification ┆   ┆ ---     ┆ Specification ┆ ---  ┆ ---   │
│ str     ┆ str      ┆ str            ┆ ---           ┆   ┆ str     ┆ ---           ┆ str  ┆ str   │
│         ┆          ┆                ┆ str           ┆   ┆         ┆ str           ┆      ┆       │
╞═════════╪══════════╪════════════════╪═══════════════╪═══╪═════════╪═══════════════╪══════╪═══════╡
│ Mobile  ┆ Motorola ┆ 88EB4558       ┆ Site          ┆ … ┆ Central ┆ Snapdragon 7  ┆ 12GB ┆ 128GB │
│ Phone   ┆          ┆                ┆ candidate     ┆   ┆         ┆ Gen           ┆      ┆       │
│         ┆          ┆                ┆ activity      ┆   ┆         ┆               ┆      ┆       │
│         ┆          ┆                ┆ company …     ┆   ┆         ┆               ┆      ┆       │
│ Mobile  ┆ Samsung  ┆ 9F975B08       ┆ Energy        ┆ … ┆ Central ┆ MediaTek      ┆ 8GB  ┆ 256GB │
│ Phone   ┆          ┆                ┆ special low   ┆   ┆         ┆ Dimensity     ┆      ┆       │
│         ┆          ┆                ┆ seven place   ┆   ┆         ┆               ┆      ┆       │
│         ┆          ┆                ┆ a…            ┆   ┆         ┆               ┆      ┆       │
│ Mobile  ┆ Dell     ┆ 14932CAE       ┆ Could before  ┆ … ┆ North   ┆ Apple         ┆ 16GB ┆ 256GB │
│ Phone   ┆          ┆                ┆ almost wind   ┆   ┆         ┆ A-Series      ┆      ┆       │
│         ┆          ┆                ┆ couple …      ┆   ┆         ┆               ┆      ┆       │
│ Mobile  ┆ Motorola ┆ E3CF42BE       ┆ Responsibilit ┆ … ┆ North   ┆ MediaTek      ┆ 6GB  ┆ 64GB  │
│ Phone   ┆          ┆                ┆ y form left   ┆   ┆         ┆ Dimensity     ┆      ┆       │
│         ┆          ┆                ┆ final s…      ┆   ┆         ┆               ┆      ┆       │
│ Mobile  ┆ Apple    ┆ F54013D6       ┆ To say system ┆ … ┆ North   ┆ Snapdragon 8  ┆ 4GB  ┆ 256GB │
│ Phone   ┆          ┆                ┆ loss near     ┆   ┆         ┆ Gen           ┆      ┆       │
│         ┆          ┆                ┆ him.          ┆   ┆         ┆               ┆      ┆       │
└─────────┴──────────┴────────────────┴───────────────┴───┴─────────┴───────────────┴──────┴───────┘

In [7]:
df.columns

['Product',
 'Brand',
 'Product Code',
 'Product Specification',
 'Price',
 'Inward Date',
 'Dispatch Date',
 'Quantity Sold',
 'Customer Name',
 'Customer Location',
 'Region',
 'Processor Specification',
 'RAM',
 'ROM']

In [8]:
report = {
        "status": "PASSED",
        "errors": [],
        "warnings": [],
        "stats": {},
    }

Column check

In [9]:
required_columns = ['Brand', 'Quantity Sold', 'Dispatch Date','Region']
missing_columns = [col for col in required_columns if col not in df.columns]
if missing_columns:
    report["status"] = "FAILED"
    report["errors"].append(f"Missing required columns: {', '.join(missing_columns)}")
report

{'status': 'PASSED', 'errors': [], 'warnings': [], 'stats': {}}

Data type check

In [10]:
# Ensure 'Date' is parseable as date
try:
    df = df.with_columns([
        pl.col("Dispatch Date").str.strptime(pl.Date, format="%Y-%m-%d"),
        pl.col("Inward Date").str.strptime(pl.Date, format="%Y-%m-%d")
    ])
    report["stats"]["date_conversion"] = "OK"
except Exception as e:
    report["status"] = "FAILED"
    report["stats"]["date_conversion"] = "FAILED"
    report["errors"].append(f"Error occurred while converting dates: {e}")
report

{'status': 'PASSED',
 'errors': [],
 'warnings': [],
 'stats': {'date_conversion': 'OK'}}

In [11]:
# Ensure 'Quantity Sold' is numeric

if df['Quantity Sold'].dtype not in [pl.Int64]:
    report["status"] = "FAILED"
    report["errors"].append("'Quantity Sold' is not numeric")
    report["stats"]["quantity_sold_type"] = "FAILED"
report

{'status': 'PASSED',
 'errors': [],
 'warnings': [],
 'stats': {'date_conversion': 'OK'}}

Null Value Checks

In [12]:
null_counts = df.null_count()

null_columns = [col for col in df.columns if null_counts[col][0] > 0]
if null_columns:
    report["status"] = "FAILED"
    report["errors"].append(f"Columns with null values: {', '.join(null_columns)}")
    report["stats"]["null_columns"] = {col: null_counts[col][0] for col in null_columns}
report

{'status': 'PASSED',
 'errors': [],
 'warnings': [],
 'stats': {'date_conversion': 'OK'}}

Range & Value Constraints

In [13]:
# Quantity Sold must be >= 0
df["Quantity Sold"]
if df["Quantity Sold"].min() < 0:
    report["status"] = "FAILED"
    report["errors"].append("'Quantity Sold' contains negative values")
    report["stats"]["quantity_sold_min"] = df["Quantity Sold"].min()
report

{'status': 'PASSED',
 'errors': [],
 'warnings': [],
 'stats': {'date_conversion': 'OK'}}

In [14]:
# Price must be >= 0
if df["Price"].min() < 0:
    report["status"] = "FAILED"
    report["errors"].append("'Price' contains negative values")
    report["stats"]["price_min"] = df["Price"].min()
report

{'status': 'PASSED',
 'errors': [],
 'warnings': [],
 'stats': {'date_conversion': 'OK'}}

Duplicate Rows

In [15]:
duplicates = df.is_duplicated()
if duplicates.any():
    report["status"] = "FAILED"
    report["errors"].append("Duplicate rows found")
    report["stats"]["duplicate_rows"] = duplicates.sum()
report

{'status': 'PASSED',
 'errors': [],
 'warnings': [],
 'stats': {'date_conversion': 'OK'}}

Data Freshness

In [16]:
date_max = df["Dispatch Date"].cast(pl.String).str.strptime(pl.Date, format="%Y-%m-%d").max()
date_max

datetime.date(2025, 5, 18)

In [17]:
today = datetime.now().date()
today

datetime.date(2026, 8, 30)

In [18]:
if date_max > today:
    report["status"] = "FAILED"
    report["errors"].append(f"'Dispatch Date' contains future dates: {date_max}")
    report["stats"]["dispatch_date_max"] = date_max

In [19]:
report

{'status': 'PASSED',
 'errors': [],
 'warnings': [],
 'stats': {'date_conversion': 'OK'}}

In [20]:
df[5:15]

shape: (10, 14)
┌──────────────┬─────────┬──────────────┬──────────────┬───┬─────────┬──────────────┬──────┬───────┐
│ Product      ┆ Brand   ┆ Product Code ┆ Product Spec ┆ … ┆ Region  ┆ Processor    ┆ RAM  ┆ ROM   │
│ ---          ┆ ---     ┆ ---          ┆ ification    ┆   ┆ ---     ┆ Specificatio ┆ ---  ┆ ---   │
│ str          ┆ str     ┆ str          ┆ ---          ┆   ┆ str     ┆ n            ┆ str  ┆ str   │
│              ┆         ┆              ┆ str          ┆   ┆         ┆ ---          ┆      ┆       │
│              ┆         ┆              ┆              ┆   ┆         ┆ str          ┆      ┆       │
╞══════════════╪═════════╪══════════════╪══════════════╪═══╪═════════╪══════════════╪══════╪═══════╡
│ Mobile Phone ┆ Toshiba ┆ 38604169     ┆ At American  ┆ … ┆ East    ┆ Snapdragon   ┆ 6GB  ┆ 512GB │
│              ┆         ┆              ┆ discussion   ┆   ┆         ┆ 7s           ┆      ┆       │
│              ┆         ┆              ┆ travel bu…   ┆   ┆         ┆              ┆      ┆       │
│ Mobile Phone ┆ Realme  ┆ E1DA13C1     ┆ Building eye ┆ … ┆ West    ┆ Snapdragon 7 ┆ 16GB ┆ 512GB │
│              ┆         ┆              ┆ media beat   ┆   ┆         ┆ Gen          ┆      ┆       │
│              ┆         ┆              ┆ until to…    ┆   ┆         ┆              ┆      ┆       │
│ Mobile Phone ┆ Samsung ┆ 00A8F8A0     ┆ Environment  ┆ … ┆ East    ┆ MediaTek     ┆ 16GB ┆ 256GB │
│              ┆         ┆              ┆ wish certain ┆   ┆         ┆ Helio        ┆      ┆       │
│              ┆         ┆              ┆ about s…     ┆   ┆         ┆              ┆      ┆       │
│ Mobile Phone ┆ HP      ┆ CF70EFC5     ┆ Opportunity  ┆ … ┆ North   ┆ Apple        ┆ 12GB ┆ 128GB │
│              ┆         ┆              ┆ work half    ┆   ┆         ┆ A-Series     ┆      ┆       │
│              ┆         ┆              ┆ certain ph…  ┆   ┆         ┆              ┆      ┆       │
│ …            ┆ …       ┆ …            ┆ …            ┆ … ┆ …       ┆ …            ┆ …    ┆ …     │
│ Mobile Phone ┆ Realme  ┆ BF018999     ┆ Or another   ┆ … ┆ West    ┆ Snapdragon   ┆ 8GB  ┆ 64GB  │
│              ┆         ┆              ┆ gun they     ┆   ┆         ┆ 7s           ┆      ┆       │
│              ┆         ┆              ┆ role growth  ┆   ┆         ┆              ┆      ┆       │
│              ┆         ┆              ┆ …            ┆   ┆         ┆              ┆      ┆       │
│ Mobile Phone ┆ HP      ┆ C98F17CA     ┆ Painting     ┆ … ┆ Central ┆ Samsung      ┆ 12GB ┆ 128GB │
│              ┆         ┆              ┆ seat process ┆   ┆         ┆ Exynos       ┆      ┆       │
│              ┆         ┆              ┆ all law hi…  ┆   ┆         ┆              ┆      ┆       │
│ Mobile Phone ┆ iQOO    ┆ F13739FF     ┆ Hair young   ┆ … ┆ South   ┆ Snapdragon 7 ┆ 16GB ┆ 512GB │
│              ┆         ┆              ┆ cause own    ┆   ┆         ┆ Gen          ┆      ┆       │
│              ┆         ┆              ┆ drop despit… ┆   ┆         ┆              ┆      ┆       │
│ Mobile Phone ┆ Dell    ┆ BDAB9D30     ┆ Thus his     ┆ … ┆ North   ┆ Snapdragon 8 ┆ 32GB ┆ 512GB │
│              ┆         ┆              ┆ however      ┆   ┆         ┆ Gen          ┆      ┆       │
│              ┆         ┆              ┆ large        ┆   ┆         ┆              ┆      ┆       │
│              ┆         ┆              ┆ suddenly …   ┆   ┆         ┆              ┆      ┆       │
└──────────────┴─────────┴──────────────┴──────────────┴───┴─────────┴──────────────┴──────┴───────┘