In [1]:
import polars as pl
import boto3
import os
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

True

In [ ]:
aws_access_key_id = os.getenv("AWS_ACCESS_KEY_ID")
aws_secret_access_key = os.getenv("AWS_SECRET_ACCESS_KEY")
endpoint_url = os.getenv("MLFLOW_S3_ENDPOINT_URL")
bucket_name = os.getenv("INPUT_BUCKET")
bucket_key = os.getenv("INPUT_KEY")
bucket_key

'mobile_sales_data.csv'

In [4]:
s3 = boto3.client(
    "s3",
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    endpoint_url=endpoint_url
)

In [5]:
obj = s3.get_object(Bucket=bucket_name, Key=bucket_key)

In [6]:
df =pl.read_csv(obj['Body'])

Filter bad data  
Remove negatives and future dates

In [7]:
df = df.filter(
    (pl.col("Price") >= 0) &
    (pl.col("Quantity Sold") >= 0) &
    (pl.col("Dispatch Date").str.strptime(pl.Date, format="%Y-%m-%d") <= datetime.now().date())
)

Parse Dates

In [8]:
df = df.with_columns([
    pl.col("Inward Date").str.strptime(pl.Date, format="%Y-%m-%d").alias("Inward Date"),
    pl.col("Dispatch Date").str.strptime(pl.Date, format="%Y-%m-%d").alias("Dispatch Date"),
])

Feature Engineering Steps

Time-based features

In [10]:
df = df.with_columns([
    pl.col("Dispatch Date").dt.year().alias("dispatch_year"),
    pl.col("Dispatch Date").dt.month().alias("dispatch_month"),
    pl.col("Dispatch Date").dt.weekday().alias("dispatch_day_of_week"),  # Monday=1, Sunday=7
    pl.col("Dispatch Date").dt.day().alias("dispatch_day"),
])
df.head()

shape: (5, 18)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Product   ┆ Brand    ┆ Product   ┆ Product   ┆ … ┆ dispatch_ ┆ dispatch_ ┆ dispatch_ ┆ dispatch_ │
│ ---       ┆ ---      ┆ Code      ┆ Specifica ┆   ┆ year      ┆ month     ┆ day_of_we ┆ day       │
│ str       ┆ str      ┆ ---       ┆ tion      ┆   ┆ ---       ┆ ---       ┆ ek        ┆ ---       │
│           ┆          ┆ str       ┆ ---       ┆   ┆ i32       ┆ i8        ┆ ---       ┆ i8        │
│           ┆          ┆           ┆ str       ┆   ┆           ┆           ┆ i8        ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Mobile    ┆ Motorola ┆ 88EB4558  ┆ Site      ┆ … ┆ 2023      ┆ 8         ┆ 4         ┆ 3         │
│ Phone     ┆          ┆           ┆ candidate ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ activity  ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ company … ┆   ┆           ┆           ┆           ┆           │
│ Mobile    ┆ Samsung  ┆ 9F975B08  ┆ Energy    ┆ … ┆ 2025      ┆ 3         ┆ 4         ┆ 20        │
│ Phone     ┆          ┆           ┆ special   ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ low seven ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ place a…  ┆   ┆           ┆           ┆           ┆           │
│ Mobile    ┆ Dell     ┆ 14932CAE  ┆ Could     ┆ … ┆ 2023      ┆ 10        ┆ 1         ┆ 16        │
│ Phone     ┆          ┆           ┆ before    ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ almost    ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ wind      ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ couple …  ┆   ┆           ┆           ┆           ┆           │
│ Mobile    ┆ Motorola ┆ E3CF42BE  ┆ Responsib ┆ … ┆ 2025      ┆ 3         ┆ 4         ┆ 20        │
│ Phone     ┆          ┆           ┆ ility     ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ form left ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ final s…  ┆   ┆           ┆           ┆           ┆           │
│ Mobile    ┆ Apple    ┆ F54013D6  ┆ To say    ┆ … ┆ 2023      ┆ 4         ┆ 3         ┆ 19        │
│ Phone     ┆          ┆           ┆ system    ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ loss near ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆           ┆ him.      ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Derived Metrics (Inventory Turnover)

In [22]:
df = df.with_columns(
    (pl.col("Dispatch Date") - pl.col("Inward Date")).dt.total_days().alias("days_to_sell")
)


df.head()

shape: (5, 27)
┌────────────┬──────────┬────────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ Product    ┆ Brand    ┆ Product    ┆ Product   ┆ … ┆ ram_code ┆ rom_code ┆ spec_leng ┆ days_to_s │
│ ---        ┆ ---      ┆ Code       ┆ Specifica ┆   ┆ ---      ┆ ---      ┆ th        ┆ ell       │
│ str        ┆ str      ┆ ---        ┆ tion      ┆   ┆ u32      ┆ u32      ┆ ---       ┆ ---       │
│            ┆          ┆ str        ┆ ---       ┆   ┆          ┆          ┆ u32       ┆ i64       │
│            ┆          ┆            ┆ str       ┆   ┆          ┆          ┆           ┆           │
╞════════════╪══════════╪════════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ Mobile     ┆ Motorola ┆ 88EB4558   ┆ Site      ┆ … ┆ 0        ┆ 0        ┆ 76        ┆ 1         │
│ Phone      ┆          ┆            ┆ candidate ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ activity  ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ company … ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Samsung  ┆ 9F975B08   ┆ Energy    ┆ … ┆ 1        ┆ 1        ┆ 40        ┆ 1         │
│ Phone      ┆          ┆            ┆ special   ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ low seven ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ place a…  ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Dell     ┆ 14932CAE   ┆ Could     ┆ … ┆ 2        ┆ 1        ┆ 57        ┆ 6         │
│ Phone      ┆          ┆            ┆ before    ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ almost    ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ wind      ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ couple …  ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Motorola ┆ E3CF42BE   ┆ Responsib ┆ … ┆ 3        ┆ 2        ┆ 79        ┆ 39        │
│ Phone      ┆          ┆            ┆ ility     ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ form left ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ final s…  ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Apple    ┆ F54013D6   ┆ To say    ┆ … ┆ 4        ┆ 1        ┆ 28        ┆ 16        │
│ Phone      ┆          ┆            ┆ system    ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ loss near ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ him.      ┆   ┆          ┆          ┆           ┆           │
└────────────┴──────────┴────────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

Derived Metrics (Revenue)

In [23]:
df = df.with_columns(
    (pl.col("Price") * pl.col("Quantity Sold")).alias("Revenue")
)
df.head()

shape: (5, 27)
┌────────────┬──────────┬────────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ Product    ┆ Brand    ┆ Product    ┆ Product   ┆ … ┆ ram_code ┆ rom_code ┆ spec_leng ┆ days_to_s │
│ ---        ┆ ---      ┆ Code       ┆ Specifica ┆   ┆ ---      ┆ ---      ┆ th        ┆ ell       │
│ str        ┆ str      ┆ ---        ┆ tion      ┆   ┆ u32      ┆ u32      ┆ ---       ┆ ---       │
│            ┆          ┆ str        ┆ ---       ┆   ┆          ┆          ┆ u32       ┆ i64       │
│            ┆          ┆            ┆ str       ┆   ┆          ┆          ┆           ┆           │
╞════════════╪══════════╪════════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ Mobile     ┆ Motorola ┆ 88EB4558   ┆ Site      ┆ … ┆ 0        ┆ 0        ┆ 76        ┆ 1         │
│ Phone      ┆          ┆            ┆ candidate ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ activity  ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ company … ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Samsung  ┆ 9F975B08   ┆ Energy    ┆ … ┆ 1        ┆ 1        ┆ 40        ┆ 1         │
│ Phone      ┆          ┆            ┆ special   ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ low seven ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ place a…  ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Dell     ┆ 14932CAE   ┆ Could     ┆ … ┆ 2        ┆ 1        ┆ 57        ┆ 6         │
│ Phone      ┆          ┆            ┆ before    ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ almost    ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ wind      ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ couple …  ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Motorola ┆ E3CF42BE   ┆ Responsib ┆ … ┆ 3        ┆ 2        ┆ 79        ┆ 39        │
│ Phone      ┆          ┆            ┆ ility     ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ form left ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ final s…  ┆   ┆          ┆          ┆           ┆           │
│ Mobile     ┆ Apple    ┆ F54013D6   ┆ To say    ┆ … ┆ 4        ┆ 1        ┆ 28        ┆ 16        │
│ Phone      ┆          ┆            ┆ system    ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ loss near ┆   ┆          ┆          ┆           ┆           │
│            ┆          ┆            ┆ him.      ┆   ┆          ┆          ┆           ┆           │
└────────────┴──────────┴────────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

Aggregated Features  
1) Average Price per Brand

In [12]:
brand_avg_price = df.group_by("Brand").agg(
    pl.col("Price").mean().alias("avg_price_per_brand")
)
brand_avg_price

shape: (20, 2)
┌─────────┬─────────────────────┐
│ Brand   ┆ avg_price_per_brand │
│ ---     ┆ ---                 │
│ str     ┆ f64                 │
╞═════════╪═════════════════════╡
│ Nokia   ┆ 103626.378717       │
│ Acer    ┆ 103494.328811       │
│ Realme  ┆ 100839.122705       │
│ Google  ┆ 103910.344376       │
│ …       ┆ …                   │
│ Samsung ┆ 103993.488871       │
│ Asus    ┆ 103072.975732       │
│ Huawei  ┆ 101821.527132       │
│ Redmi   ┆ 100484.434992       │
└─────────┴─────────────────────┘

In [13]:
df = df.join(brand_avg_price, on="Brand", how="left")
df.head()

shape: (5, 20)
┌────────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ Product    ┆ Brand    ┆ Product    ┆ Product   ┆ … ┆ dispatch_ ┆ dispatch_ ┆ Revenue ┆ avg_price │
│ ---        ┆ ---      ┆ Code       ┆ Specifica ┆   ┆ day_of_we ┆ day       ┆ ---     ┆ _per_bran │
│ str        ┆ str      ┆ ---        ┆ tion      ┆   ┆ ek        ┆ ---       ┆ i64     ┆ d         │
│            ┆          ┆ str        ┆ ---       ┆   ┆ ---       ┆ i8        ┆         ┆ ---       │
│            ┆          ┆            ┆ str       ┆   ┆ i8        ┆           ┆         ┆ f64       │
╞════════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ Mobile     ┆ Motorola ┆ 88EB4558   ┆ Site      ┆ … ┆ 4         ┆ 3         ┆ 471420  ┆ 102969.75 │
│ Phone      ┆          ┆            ┆ candidate ┆   ┆           ┆           ┆         ┆ 4125      │
│            ┆          ┆            ┆ activity  ┆   ┆           ┆           ┆         ┆           │
│            ┆          ┆            ┆ company … ┆   ┆           ┆           ┆         ┆           │
│ Mobile     ┆ Samsung  ┆ 9F975B08   ┆ Energy    ┆ … ┆ 4         ┆ 20        ┆ 799130  ┆ 103993.48 │
│ Phone      ┆          ┆            ┆ special   ┆   ┆           ┆           ┆         ┆ 8871      │
│            ┆          ┆            ┆ low seven ┆   ┆           ┆           ┆         ┆           │
│            ┆          ┆            ┆ place a…  ┆   ┆           ┆           ┆         ┆           │
│ Mobile     ┆ Dell     ┆ 14932CAE   ┆ Could     ┆ … ┆ 1         ┆ 16        ┆ 70020   ┆ 103043.38 │
│ Phone      ┆          ┆            ┆ before    ┆   ┆           ┆           ┆         ┆ 8109      │
│            ┆          ┆            ┆ almost    ┆   ┆           ┆           ┆         ┆           │
│            ┆          ┆            ┆ wind      ┆   ┆           ┆           ┆         ┆           │
│            ┆          ┆            ┆ couple …  ┆   ┆           ┆           ┆         ┆           │
│ Mobile     ┆ Motorola ┆ E3CF42BE   ┆ Responsib ┆ … ┆ 4         ┆ 20        ┆ 1746980 ┆ 102969.75 │
│ Phone      ┆          ┆            ┆ ility     ┆   ┆           ┆           ┆         ┆ 4125      │
│            ┆          ┆            ┆ form left ┆   ┆           ┆           ┆         ┆           │
│            ┆          ┆            ┆ final s…  ┆   ┆           ┆           ┆         ┆           │
│ Mobile     ┆ Apple    ┆ F54013D6   ┆ To say    ┆ … ┆ 3         ┆ 19        ┆ 461259  ┆ 102809.73 │
│ Phone      ┆          ┆            ┆ system    ┆   ┆           ┆           ┆         ┆ 4362      │
│            ┆          ┆            ┆ loss near ┆   ┆           ┆           ┆         ┆           │
│            ┆          ┆            ┆ him.      ┆   ┆           ┆           ┆         ┆           │
└────────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

Average Quantity Sold per Region

In [15]:
region_avg_qty = df.group_by("Region").agg(
    pl.col("Quantity Sold").mean().alias("avg_qty_per_region")
)
region_avg_qty

shape: (5, 2)
┌─────────┬────────────────────┐
│ Region  ┆ avg_qty_per_region │
│ ---     ┆ ---                │
│ str     ┆ f64                │
╞═════════╪════════════════════╡
│ West    ┆ 5.492646           │
│ Central ┆ 5.534659           │
│ East    ┆ 5.562679           │
│ North   ┆ 5.474654           │
│ South   ┆ 5.489637           │
└─────────┴────────────────────┘

In [16]:
df = df.join(region_avg_qty, on="Region", how="left")
df.head()

shape: (5, 21)
┌────────────┬──────────┬────────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ Product    ┆ Brand    ┆ Product    ┆ Product   ┆ … ┆ dispatch_ ┆ Revenue ┆ avg_price ┆ avg_qty_p │
│ ---        ┆ ---      ┆ Code       ┆ Specifica ┆   ┆ day       ┆ ---     ┆ _per_bran ┆ er_region │
│ str        ┆ str      ┆ ---        ┆ tion      ┆   ┆ ---       ┆ i64     ┆ d         ┆ ---       │
│            ┆          ┆ str        ┆ ---       ┆   ┆ i8        ┆         ┆ ---       ┆ f64       │
│            ┆          ┆            ┆ str       ┆   ┆           ┆         ┆ f64       ┆           │
╞════════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ Mobile     ┆ Motorola ┆ 88EB4558   ┆ Site      ┆ … ┆ 3         ┆ 471420  ┆ 102969.75 ┆ 5.534659  │
│ Phone      ┆          ┆            ┆ candidate ┆   ┆           ┆         ┆ 4125      ┆           │
│            ┆          ┆            ┆ activity  ┆   ┆           ┆         ┆           ┆           │
│            ┆          ┆            ┆ company … ┆   ┆           ┆         ┆           ┆           │
│ Mobile     ┆ Samsung  ┆ 9F975B08   ┆ Energy    ┆ … ┆ 20        ┆ 799130  ┆ 103993.48 ┆ 5.534659  │
│ Phone      ┆          ┆            ┆ special   ┆   ┆           ┆         ┆ 8871      ┆           │
│            ┆          ┆            ┆ low seven ┆   ┆           ┆         ┆           ┆           │
│            ┆          ┆            ┆ place a…  ┆   ┆           ┆         ┆           ┆           │
│ Mobile     ┆ Dell     ┆ 14932CAE   ┆ Could     ┆ … ┆ 16        ┆ 70020   ┆ 103043.38 ┆ 5.474654  │
│ Phone      ┆          ┆            ┆ before    ┆   ┆           ┆         ┆ 8109      ┆           │
│            ┆          ┆            ┆ almost    ┆   ┆           ┆         ┆           ┆           │
│            ┆          ┆            ┆ wind      ┆   ┆           ┆         ┆           ┆           │
│            ┆          ┆            ┆ couple …  ┆   ┆           ┆         ┆           ┆           │
│ Mobile     ┆ Motorola ┆ E3CF42BE   ┆ Responsib ┆ … ┆ 20        ┆ 1746980 ┆ 102969.75 ┆ 5.474654  │
│ Phone      ┆          ┆            ┆ ility     ┆   ┆           ┆         ┆ 4125      ┆           │
│            ┆          ┆            ┆ form left ┆   ┆           ┆         ┆           ┆           │
│            ┆          ┆            ┆ final s…  ┆   ┆           ┆         ┆           ┆           │
│ Mobile     ┆ Apple    ┆ F54013D6   ┆ To say    ┆ … ┆ 19        ┆ 461259  ┆ 102809.73 ┆ 5.474654  │
│ Phone      ┆          ┆            ┆ system    ┆   ┆           ┆         ┆ 4362      ┆           │
│            ┆          ┆            ┆ loss near ┆   ┆           ┆         ┆           ┆           │
│            ┆          ┆            ┆ him.      ┆   ┆           ┆         ┆           ┆           │
└────────────┴──────────┴────────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

Categorical Encoding (Convert text to numbers)  
Use simple label encoding for Brand, Region, RAM, ROM  
Polars has a built-in `to_physical()` for categoricals

In [17]:
df = df.with_columns([
    pl.col("Brand").cast(pl.Categorical).to_physical().alias("brand_code"),
    pl.col("Region").cast(pl.Categorical).to_physical().alias("region_code"),
    pl.col("RAM").cast(pl.Categorical).to_physical().alias("ram_code"),
    pl.col("ROM").cast(pl.Categorical).to_physical().alias("rom_code"),
])
df.head()

shape: (5, 25)
┌────────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ Product    ┆ Brand    ┆ Product    ┆ Product   ┆ … ┆ brand_cod ┆ region_co ┆ ram_code ┆ rom_code │
│ ---        ┆ ---      ┆ Code       ┆ Specifica ┆   ┆ e         ┆ de        ┆ ---      ┆ ---      │
│ str        ┆ str      ┆ ---        ┆ tion      ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32      │
│            ┆          ┆ str        ┆ ---       ┆   ┆ u32       ┆ u32       ┆          ┆          │
│            ┆          ┆            ┆ str       ┆   ┆           ┆           ┆          ┆          │
╞════════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ Mobile     ┆ Motorola ┆ 88EB4558   ┆ Site      ┆ … ┆ 0         ┆ 0         ┆ 0        ┆ 0        │
│ Phone      ┆          ┆            ┆ candidate ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ activity  ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ company … ┆   ┆           ┆           ┆          ┆          │
│ Mobile     ┆ Samsung  ┆ 9F975B08   ┆ Energy    ┆ … ┆ 1         ┆ 0         ┆ 1        ┆ 1        │
│ Phone      ┆          ┆            ┆ special   ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ low seven ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ place a…  ┆   ┆           ┆           ┆          ┆          │
│ Mobile     ┆ Dell     ┆ 14932CAE   ┆ Could     ┆ … ┆ 2         ┆ 1         ┆ 2        ┆ 1        │
│ Phone      ┆          ┆            ┆ before    ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ almost    ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ wind      ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ couple …  ┆   ┆           ┆           ┆          ┆          │
│ Mobile     ┆ Motorola ┆ E3CF42BE   ┆ Responsib ┆ … ┆ 0         ┆ 1         ┆ 3        ┆ 2        │
│ Phone      ┆          ┆            ┆ ility     ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ form left ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ final s…  ┆   ┆           ┆           ┆          ┆          │
│ Mobile     ┆ Apple    ┆ F54013D6   ┆ To say    ┆ … ┆ 3         ┆ 1         ┆ 4        ┆ 1        │
│ Phone      ┆          ┆            ┆ system    ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ loss near ┆   ┆           ┆           ┆          ┆          │
│            ┆          ┆            ┆ him.      ┆   ┆           ┆           ┆          ┆          │
└────────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴──────────┘

Text Feature (Length of Product Specification - quick proxy for descriptiveness)

In [18]:
df = df.with_columns(
    pl.col("Product Specification").str.len_chars().alias("spec_length")
)
df.head()

shape: (5, 26)
┌────────────┬──────────┬────────────┬───────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ Product    ┆ Brand    ┆ Product    ┆ Product   ┆ … ┆ region_co ┆ ram_code ┆ rom_code ┆ spec_leng │
│ ---        ┆ ---      ┆ Code       ┆ Specifica ┆   ┆ de        ┆ ---      ┆ ---      ┆ th        │
│ str        ┆ str      ┆ ---        ┆ tion      ┆   ┆ ---       ┆ u32      ┆ u32      ┆ ---       │
│            ┆          ┆ str        ┆ ---       ┆   ┆ u32       ┆          ┆          ┆ u32       │
│            ┆          ┆            ┆ str       ┆   ┆           ┆          ┆          ┆           │
╞════════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ Mobile     ┆ Motorola ┆ 88EB4558   ┆ Site      ┆ … ┆ 0         ┆ 0        ┆ 0        ┆ 76        │
│ Phone      ┆          ┆            ┆ candidate ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ activity  ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ company … ┆   ┆           ┆          ┆          ┆           │
│ Mobile     ┆ Samsung  ┆ 9F975B08   ┆ Energy    ┆ … ┆ 0         ┆ 1        ┆ 1        ┆ 40        │
│ Phone      ┆          ┆            ┆ special   ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ low seven ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ place a…  ┆   ┆           ┆          ┆          ┆           │
│ Mobile     ┆ Dell     ┆ 14932CAE   ┆ Could     ┆ … ┆ 1         ┆ 2        ┆ 1        ┆ 57        │
│ Phone      ┆          ┆            ┆ before    ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ almost    ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ wind      ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ couple …  ┆   ┆           ┆          ┆          ┆           │
│ Mobile     ┆ Motorola ┆ E3CF42BE   ┆ Responsib ┆ … ┆ 1         ┆ 3        ┆ 2        ┆ 79        │
│ Phone      ┆          ┆            ┆ ility     ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ form left ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ final s…  ┆   ┆           ┆          ┆          ┆           │
│ Mobile     ┆ Apple    ┆ F54013D6   ┆ To say    ┆ … ┆ 1         ┆ 4        ┆ 1        ┆ 28        │
│ Phone      ┆          ┆            ┆ system    ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ loss near ┆   ┆           ┆          ┆          ┆           │
│            ┆          ┆            ┆ him.      ┆   ┆           ┆          ┆          ┆           │
└────────────┴──────────┴────────────┴───────────┴───┴───────────┴──────────┴──────────┴───────────┘

Select the Final Feature Set

In [19]:
final_columns = [
    # Target variable (What we want to predict)
    "Quantity Sold",
    # Numeric/Date features
    "Price",
    "days_to_sell",
    "Revenue",
    "dispatch_year",
    "dispatch_month",
    "dispatch_day_of_week",
    "spec_length",
    # Encoded categoricals
    "brand_code",
    "region_code",
    "ram_code",
    "rom_code",
    # Aggregated features (added context)
    "avg_price_per_brand",
    "avg_qty_per_region",
]

Create the feature DataFrame

In [24]:
feature_df = df.select(final_columns)
feature_df.head(5)

shape: (5, 14)
┌─────────────┬────────┬─────────────┬─────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ Quantity    ┆ Price  ┆ days_to_sel ┆ Revenue ┆ … ┆ ram_code ┆ rom_code ┆ avg_price_ ┆ avg_qty_pe │
│ Sold        ┆ ---    ┆ l           ┆ ---     ┆   ┆ ---      ┆ ---      ┆ per_brand  ┆ r_region   │
│ ---         ┆ i64    ┆ ---         ┆ i64     ┆   ┆ u32      ┆ u32      ┆ ---        ┆ ---        │
│ i64         ┆        ┆ i64         ┆         ┆   ┆          ┆          ┆ f64        ┆ f64        │
╞═════════════╪════════╪═════════════╪═════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 6           ┆ 78570  ┆ 1           ┆ 471420  ┆ … ┆ 0        ┆ 0        ┆ 102969.754 ┆ 5.534659   │
│             ┆        ┆             ┆         ┆   ┆          ┆          ┆ 125        ┆            │
│ 5           ┆ 159826 ┆ 1           ┆ 799130  ┆ … ┆ 1        ┆ 1        ┆ 103993.488 ┆ 5.534659   │
│             ┆        ┆             ┆         ┆   ┆          ┆          ┆ 871        ┆            │
│ 6           ┆ 11670  ┆ 6           ┆ 70020   ┆ … ┆ 2        ┆ 1        ┆ 103043.388 ┆ 5.474654   │
│             ┆        ┆             ┆         ┆   ┆          ┆          ┆ 109        ┆            │
│ 10          ┆ 174698 ┆ 39          ┆ 1746980 ┆ … ┆ 3        ┆ 2        ┆ 102969.754 ┆ 5.474654   │
│             ┆        ┆             ┆         ┆   ┆          ┆          ┆ 125        ┆            │
│ 9           ┆ 51251  ┆ 16          ┆ 461259  ┆ … ┆ 4        ┆ 1        ┆ 102809.734 ┆ 5.474654   │
│             ┆        ┆             ┆         ┆   ┆          ┆          ┆ 362        ┆            │
└─────────────┴────────┴─────────────┴─────────┴───┴──────────┴──────────┴────────────┴────────────┘

Handle Nulls

In [25]:
feature_df = feature_df.fill_null(0)

In [26]:
feature_df.shape

(24983, 14)

Save to MinIO for the Training Pipeline

In [27]:
local_feature_file = "processed_features.parquet"
feature_df.write_parquet(local_feature_file)

In [ ]:
OUTPUT_BUCKET = "processed-features"
OUTPUT_KEY = f"features_{datetime.now().strftime('%Y-%m-%d')}.parquet"

In [ ]:
s3.upload_file(local_feature_file, OUTPUT_BUCKET, OUTPUT_KEY)

In [ ]:
with open("/tmp/output_uri.txt", "w") as f:
    f.write(f"s3://{OUTPUT_BUCKET}/{OUTPUT_KEY}")